### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by andyfriesen** [cruxlang/crux#42]
Strawman:

tldr: Do exactly what OCaml does.

All exceptions are conceptually variants of an application-wide extensible sum.  We introduce the `exception` keyword to add another error type to this mega-sum.  We introduce `throw` as the keyword for throwing an exception.

Exception handling works like pattern matching.

```
data FileNotFound { FileNotFound }
exception FileNotFound
fun notFound() { throw FileNotFound; }

data IndexError { IndexError(Number) }
exception IndexError

fun f() {
    let a = [];
    try {
        a[0]
    } with {
        FileNotFound => {
            ...
        },
        IndexError(idx) => {
            print("Index error! " + toString(idx));
        }
    };
}
```

**Comment by chadaustin** [comment]
I think it might be helpful to separate out the runtime semantics from the syntax and higher-level structure of exceptions.

Figuring out the runtime semantics is higher-priority.  As a first sketch, we could copy the semantics of JavaScript or GHC RTS: any value is throwable and catchable.  Do we support RAII?  I'd guess convenient RAII costs a fair amount of perf in JS due to all the try { ... } finally { ... }.  Last I checked, V8 disables optimizations on functions that use exceptions.  @kg might have more recent info.

Syntactically, I think an exception hierarchy is valuable, largely because filtering on exception categories is so common.  I'm inlined not to innovate too much here.

Thoughts?

**Comment by kg** [comment]
try-catch is definitely still a deopt in v8, but i haven't tested try-finally recently.

the last time i checked, 'throw' is also a deopt in both spidermonkey and v8. you can get around that by putting the throw in its own function and calling the throw-function.

the chrome profiler shows little /!\ icons next to deopted functions now, so you should be able to profile an optimized test case and see if try-finally functions are being deopted.

**Comment by chadaustin** [comment]
Crux now has a rough first pass at exceptions.  Let's open new issues for proposed changes, whether they be syntax or semantics.

I'm open to polymorphic variants but hierarchies are useful too.
