### ISSUE TITLE
not sound under mutability

### ISSUE THREAD

**Issue by chadaustin** [cruxlang/crux#80]
This typechecks today:

```
let a = []
a->append(1)
a->append("hi")
```

We need to make sure only immutable data is quantified in let bindings.

We could go the ocaml route and have "weak type variables" that can only be unified once, but are frozen thereafter.  These would not be exportable of course.

**Comment by chadaustin** [comment]
We might want something like ocaml's value restriction.

https://realworldocaml.org/v1/en/html/imperative-programming-1.html#side-effects-and-weak-polymorphism

**Comment by andyfriesen** [comment]
I think weak polymorphism will work brilliantly for us.

The following types of expressions should initially unify with a weakly polymorphic type variable:

`let mutable a = None`
`let a = mutable []`
`let a = { mutable field: None }`

Weakly polymorphic type variables basically behave like free type variables in that they are replaced with the first concrete type they are unified with.

Consider the following example (translated from the OCaml documentation):

```
let remember = (
    let mutable cache = None;
    fun (x) {
        match cache {
            None => (cache = x ; x);
            Some y => y;
        }
    }
)
```

When typechecking this function, we first ascribe the type `Option a` to the expression `None`.  `cache`, however, is mutable, so we'll traverse this typevar and replace `a` with `_a` (make it weakly polymorphic).

The next time `remember` is used, we'll unify `_a` as in the same way we would if it were free.

**Comment by andyfriesen** [comment]
I do not have terrific confidence that https://github.com/cruxlang/crux/commit/ea8eec81fa08673233a264be8fe0972f1baabc36 is truly the best solution here, but it will always err on the side of overconstraining programs.

I think this means that the type system is sound, but it may interfere with valid programs where universal quantification is safe, like the following:

```
let a : { x : Option a } = { x : None }

let b : { x : Option Number } = a
let c : { x : Option String } = a
```

The definitions `b` and `c` are actually safe because the field `x` is immutable and we presently assume uniform representation.  This is nevertheless forbidden by the Crux type system for now.
